### ISSUE TITLE
Update animation time / remove animations

### ISSUE THREAD

**Issue by laurensdc** [perfect-things/perfect-home#107]
There is no way to override the current animation settings as they are applied inline with JS. Any way to fix?

**Comment by tborychowski** [comment]
can you be more specific?
which animations do you mean, there are several different ones in different places?

**Comment by laurensdc** [comment]
When clicking a bookmark, the view updates to the subdirectory with a fade out & fade in animation.
It is when clicking an `<a class=".item .item-folder">` an inline style `animation: 150ms linear` gets added.

**Comment by tborychowski** [comment]
Aah, this one. This one actually comes from the js framework that I use (svelte), as you can see here:
https://github.com/perfect-things/perfect-home/blob/master/src/tile/index.svelte#L10-L11

However, it is still possible to have it controlled from css, e.g. using css custom properties.
I can add that feature.

May I ask what's the reason for this request?
Is it just aesthetics (you don't like this animation), accessibility (you can't view content with animations) or something else?
(just curious, as there may be an issue that is related to the problem you're having, that I'm not aware of)

**Comment by laurensdc** [comment]
I see, thanks for clearing it up!
The issue for me is that I click & open fast, and now I have to wait.
My bookmarks are organized in folders and subfolders, so it takes too long to open bookmarks.

**Comment by tborychowski** [comment]
It takes long to load all your bookmarks?
Can I ask how many do you have in a folder?

But if that's the case, I'm not sure how changing the animation will help here...
Animation (fade-out) happens as soon as you click - and all the bookmarks in the current folder are removed.
Than the new ones are loaded and (once they are loaded) then they are displayed (with the fade-in animation).
So neither removing the animation, nor prolonging it, will not change the loading time.
And I know firefox has problems with loading large numbers of bookmarks (even the built-in bookmark manager gets very slow if you have thousands of them).

**Comment by laurensdc** [comment]
It doesn't take long to load my bookmarks, it's just that the fade in and fade out animations last too long.
I believe it's 150ms fade out, then 150ms fade in. Clicking two folders deep that already takes 600ms which is quite long.
There are no problems for me rendering lots of bookmarks or nested folders.

**Comment by tborychowski** [comment]
Ok, I understand now! :-)
Thanks. 
Will add this to the next release.
