### ISSUE TITLE
Firefox for Android compatibility

### ISSUE THREAD

**Issue by ren-10** [perfect-things/perfect-home#118]
I'd love to be able to use this on Firefox for Android (I'm currently using Firefox Nightly). Love your work thanks mate. Disclaimer that I have no idea on addon portability. If this isn't possible and if you (or anyone) know of a similar alternative which works on Android please let me know!

**Comment by tborychowski** [comment]
Thanks for the feedback.
I'd love to make it work, but I don't have any device with android available for testing/debugging, and I haven't found an easy way to do that on a laptop...
(I just tested a couple of popular android emulators and none of them was suitable for dev testing).

So unless you can show me an easy way for me to do that... 
I'm sorry :-|

**Comment by Stormersh** [comment]
> 
> 
> I'd love to make it work, but I don't have any device with android available for testing/debugging, and I haven't found an easy way to do that on a laptop...
> (I just tested a couple of popular android emulators and none of them was suitable for dev testing).
> 
> So unless you can show me an easy way for me to do that...
> I'm sorry :-|

I'm sorry for opening an "old" issue, but have you tried Anbox for Ubuntu-based distros?

**Comment by tborychowski** [comment]
No I haven't.
But even that would be a bit of an overhead (to run a VM on my mac for Ubuntu, and then run the Anbox on it).
And recently my time is shorter than "0", and I cannot possibly go into this :-(
Sorry about that.

**Comment by Stormersh** [comment]
No problem, I understand. Thanks anyway! :)
