### ISSUE TITLE
Allow custom links

### ISSUE THREAD

**Issue by chaptergy** [perfect-things/perfect-home#132]
I would like to suggest adding a feature, where you can set up the page totally independent of any bookmarks folder, so more like an improved "top sites" from the native firefox home screen (without the suggestions of course). This way you could have have many different links which might be in different bookmark folders. Currently you have to duplicate the bookmarks you want to show up on your home screen into a new folder and select that folder in Perfect Home, but this would allow you to just add any link to your home screen.

Thanks!

**Comment by tborychowski** [comment]
I can see where you're coming from, but: this would mean that I need to persist that information somewhere.
Currently the only persistance (~database) an extension has access to is the browser local storage (accessible by extension API). This is not a very good database and can easily be lost.
I know some typical "SpeedDial" type extensions use either this or some remote service (which I also don't like to do for so many reasons).

Moreover, this would require a substantial design change (technical design, not necessarily visual) as currently all functionality is based around the browser's bookmarks API, which provides the required operations (read, find, sort, reorder, etc).
A similar API for a custom storage would have to be implemented and thoroughly tested with all the weirdness people have in their bookmarks (and believe me, after 5 years of working on this and 1 more extension for bookmarks, I've seen many).
And this is not a small thing to do, and would require more time and commitment than I can currently avail.

Lastly, this extension was never meant for anything more than just displaying a folder from bookmarks (like Safari, Opera, Vivaldi, and other browsers do). The whole idea was that this was very basic, minimalist design & functionality and - for the cost of that minimalism - a well tested, performant and reliable little extension that you can use 100 times a day and it will never fail.

So I do appreciate your feedback, but this not something I'd be willing to implement.
Sorry about that :-)
