### ISSUE TITLE
One problem...

### ISSUE THREAD

**Issue by ivan-volnov** [perfect-things/perfect-home#133]
It's black!

Why don't you have an option to make it look nice on white environment?

**Comment by tborychowski** [comment]
Hi Ivan,

1. to me black is `#000`, while the default bg colour for the extension is `#333` 😉 
2. for the year that this extension is available - you're the first person to ask for that.
3. the option is there already:

<img width="1310" alt="Screenshot 2021-06-14 at 14 12 17" src="https://user-images.githubusercontent.com/392513/121898205-0ebcd700-cd1b-11eb-84b7-f086899d2363.png">

I know it's not the prettiest, but it's there, and can easily be tweaked (in the `Custom CSS` box below) and lastly, I don't have time to work on this at the moment (personal matters).
