### ISSUE TITLE
How do I....

### ISSUE THREAD

**Issue by kleshas** [perfect-things/perfect-home#134]
I just came across this tool, it's great.  I've been looking for this kind of thing for a while, and had some grief from others for it.  Glad to see I'm not the only one who likes this idea of displaying browser shortcuts as a homepage.

I've been trying to customize - first off, my main folder's links never move to multiple columns like in your screenshot examples.  Always a single column, no matter how many there are.  As this happens with no customization, I asssume this is a bug with my setup (FF90, on arch w/ sway)

Is there a way of having NO shortcuts in the main page, and instead use a wallpaper, which is a variable to a changing wallpaper defined in a css, and the page is only showing the docked folders?

Can we change the placement of the docked folders?  Can we make them transparent?  Can we change their widths?

I assume a few of the answers to these are to do with css.  Is there a repository of users' setups with css?  Is there anywhere to discuss this app other than here?

**Comment by tborychowski** [comment]
Hi,

Thanks, glad that you like it :-)
As for your issue (1 column) - haven't seen that one before. 
1. Would you mind providing a screenshot?
2. Is it possible that you have another extension that runs on every page (like adblocker or similar)? Would you mind temporarily disabling other extensions and see if this still happens?
3. What's "w/ sway"? 
4. you definitely can have no shortcuts. Just create an empty folder in your bookmarks and set it as the main folder in the extension settings (you can use css to hide the name of the folder too).
5. For the wallpaper - you'd need to set `background: url();` and the url would have to provide you with a service that returns a different wallpaper e.g. every day. (let me know if you have trouble with that and I'll give you instructions).
6. yes to all :-) There is a "custom css" field so you can basically do anything you wish. See [customization tutorial](https://github.com/perfect-things/perfect-home/blob/master/customization-tutorial.md) for starters and if you have any issues/questions let me know.
7. I'm afraid that there isn't, but maybe it's time to have a reddit or something :-) leave it with me and I'll think of something! :-)
But CSS (even if you're not a web developer) is not that difficult. All you need is pop up the dev tools and check the class of an element you wish to style - and then style it :-)

**Comment by kleshas** [comment]
https://imgur.com/a/8XAts3s
I've tried this with no firefox addons enabled.  Note the scrollbar on the right - there's another icon or two beneath the visible screen you need to scroll to see.

w/ sway = with sway.  sway being the wayland compositor I'm using on arch linux.

Also, I've been fiddling around and cannot work out how to fix this issue - when I make each custom folder 1000px high, 500px is used by the folder title.  Inspecting the folder doesn't show me anything useful.

Re having a blank main page - when there's nothing in the folder then there's some text at the top telling me to add bookmarks.  Obviously I don't want that.

edit:  oddly enough if I add these two lines to the custom.css the titles of the folders DO move back to the standard height:
`@import url("file:///home/kleshas/.cache/wal/colors.css");`

`background-color: var(--color2`

Note the mistake at the end of the second line.  If it's properly formatted ie  background-color: var(--color2); then the title of the folders remains at half-height of the setting specified (1000px as above).  That said, the import doesn't seem to work as the colours don't change.

**Comment by tborychowski** [comment]
1. Screenshot - that is extremely weird. Can you do the screenshot of your "Customize" settings? (from what you're saying it looks like a weird combination of settings)
Or try "reset to defaults" and see if this still happens.

2. Blank folder: you can hide the header with "custom css":
```css
header { display: none; }
```

> when I make each custom folder 1000px high, 500px is used by the folder title

not sure I understand what you're trying to achieve here... Would you mind sketching the layout (any graphic app or even pen & paper - and post it here (you can drag & drop images directly, btw, no need to use imgur 😉)).

Is it a docked folder that you wish to extend to the full height of the screen?
if so, you can try this css:
```css
.folder { margin-top: -100vh; }
.folder-items { min-height: calc(100vh - 50px); }
```

Incorrectly formatted CSS should not work, so that's to be expected.
As for the local file import - I don't think it will work TBH. It's always better/safer to use a server (even a local apache or node). Once you have the style you like, you can then publish it to the [theme gallery](https://github.com/perfect-things/perfect-home-themes) repo :-)

**Comment by kleshas** [comment]
1.  OK, I now have multiple columns,  I guess a couple of resets were needed. (I've reset before with no effect)
2. thanks, this  hidden title code seems to work.  Yes, I want a docked folder the height of the screen, at the moment I can get the height OK, but the height is shared 50-50 by the docked folder title and the list of bookmarks.
![quick](https://user-images.githubusercontent.com/10134682/126231230-cd3d9228-8f1c-461b-894e-44fd7ef5fe93.jpg)
x it title height.  y is total height.  With this code:
```
header { display: none; }

.folder-zqO21Z1nkYq2 {
	position: fixed;
	top: 50px;
	left: 0px;
	width: 225px;
	height: 800px;
	transform: none;
	border: 1px solid black;
	border-radius: 0 25px 25px 0;
	padding: 15px 5px 15px 0;
	margin: 0 0 0 -1px !important; /* margin is set by javascript, so `!important` is needed to overwrite it */
}

.folder--iah2jb7RlPo {
	position: fixed;
	top: 50px;
	left: 250px;
	width: 225px;
	height: 800px;
	transform: none;
	border: 1px solid black;
	border-radius: 0 25px 25px 0;
	padding: 15px 5px 15px 0;
	margin: 0 0 0 -1px !important; /* margin is set by javascript, so `!important` is needed to overwrite it */
}
```

I get x=y=400px (half of the 800px defined in the css.  The thing with the background was trying to get that behind the docked folders (so mostly hidden), and that doesn't work as it changes and I was hoping that `@import url("file.css");` would work as in my other homepage.  TBH, my other homepage works great with the imported css, colours and background change when the desktop wallpaper does, but I could never figure out how to link the browser's bookmarks and make them drag-and-droppable like you have here, which is great imo.

**Comment by tborychowski** [comment]
Ok, I see what you mean now.
So did you try the CSS I've given you earlier in my previous comment?
If you use yours (position fixed, and manually specify the positions - it may not always work correctly).
Your css basically set's the height of the folder container (`.folder-<ID>`).
Mine sets the folder container to start at the top and then sets the height of the items container (`.folder-items`) to extend to the full height. So this should work for you (I added `max-height` so it does not extend beyond the screen):

```css
.folder { margin-top: -100vh; }
.folder-items { min-height: calc(100vh - 50px); max-height: calc(100vh - 50px); }
```
Just need to pin docked folders so they don't auto-collapse (the orange circle to the left of the title).

After that, you can add more styling (custom width, border, etc...)

This is how it looks in mine:
<img width="1036" alt="CleanShot 2021-07-20 at 09 26 56@2x" src="https://user-images.githubusercontent.com/392513/126288033-5b23ef20-7111-4eb2-8f37-554697518e1c.png">


As for the css-imports - there are lots of issues with importing local files like this (security limitations of the rendered content may go in the way of doing that). Not sure what other homepage/extension you used before - maybe they do something special for local files...
But - like I said - the easiest thing to do is:
- create a github repo (or even a gist)
- put the file there (also good for backup 😉)
- copy the "raw" github path
- import that instead of the local file

e.g.
```css
@import url('https://raw.githubusercontent.com/perfect-things/perfect-home-themes/master/theme-pure-white/index.css');
```

**Comment by kleshas** [comment]
OK, I have it working,  Thanks for the help.

I'll look into using github for importing .css files from.



> in the way of doing that). Not sure what other homepage/extension you used before - maybe they do something special for local files...

I have a static html file, and a .css which imports another css for the variable colours it uses to config the page.  Lots of var (--colorx); and background-image: var(--wallpaper); .  Everytime i change the system wallpaper, that referenced css gets updated with the main colours used in the wallpaper, and hence the html file gets colour changes and a new picture embedded. (the colour analysis is done via pywal if you're interested).  The only disadavantage of this is that any new link has to be done by manually embedding the html file.  That's why I love your idea - ctrl-d in the browser, move it to the correct folder, and I'm done.  No variable colours though.

**Comment by tborychowski** [comment]
Ok, I understand the use case :-)
So the best option for you would be to run a local server (e.g. `python -m SimpleHTTPServer`) and serve your css file from it, and then you could do both - have a script update the css and have it imported in PerfectHome (e.g. `url('localhost:8000/style.css`).

**Comment by kleshas** [comment]
```
@import url('localhost:8000/colors.css');

header { 
display: none;
}

body {
--color-border: #000;
	--color-background: var(--color1);
	--color-text: var(--color1);
	--color-highlight: var(--color15);
	--color-accent: orange;
	--color-info: #666d7b;
	--color-success: #408062;
	--color-warning: #af8a1a;
	--color-danger: #8b4848;
		}

.folder { 
margin-top: -100vh;
width: 325px;
height: 1200px;
padding: 0px 0px 0px 0px;
border: 1px solid black;
border-radius: 0 0px 0px 0;
position: fixed;
top: 50px;
transform: none;
margin: 0 0 0 -1px!important; /* margin is set by javascript, so `!important` is needed to overwrite it */
			}

.folder-items { min-height: calc(100vh - 50px); max-height: calc(100vh - 50px); }

.folder-zqO21Z1nkYq2 {
	left: 25px;
	}

.folder--iah2jb7RlPo {
	left: 375px;
	}

.folder-njP80kP4mXgF {
	left: 725px;
	}

.folder-dBeay7kwjwSl {
	left: 1075px;
	}

.folder-ZHL6aVpigWf7 {
	left: 1425px;
	}

.folder-mqma3aQPuoTN {
	left: 1775px;
	}

.folder-wakYyWiJ755C {
	left: 2125px;
	}
```
The colors file is served, confirmed via a browser to that link.  It's formatted properly.  However, the snippet above doesn't try to import.  I do get 200 GET's when browsing to the link.  I also tried:
```
<head>
<link rel="stylesheet" type="text/css" href="localhost:8000/colors.css">
</head>
```
The variable colors aren't used and instead use the ones defined in the upper section of the Basic Customisations area (or if I change to --color-text: white; for example, that works and overwrites the upper section of Basic Customisations, as expected.)

**Comment by tborychowski** [comment]
ups! sorry, my bad! the url must be a proper URL format, so not 'localhost:8000' but 'http://localhost:8000'.
It will work in browser addressbar, because browsers add the protocol automatically.

**Comment by kleshas** [comment]
Could've sworn I had tried that last night.  Oh well, works now, thanks.

**Comment by tborychowski** [comment]
Let me know if you have any other issues (and feel free to re-open this). Otherwise, closing :-)

**Comment by kleshas** [comment]
In the name of completion I managed to do the final issue I had in the inital post, specifically with the wallpaper being used.  pywal assigns it dynamically from another folder, and I couldn't work out how to get this app to read that changing wallpaper.


Turns out 


`cp $(cat ~/.cache/wal/wal) ~/.cache/wal/wal.jpg`


works great, where .cache/wal is the http.server base page (run this snippet after running the pywal app, and ./wal/wal will contain the new /path/to/wallpaper).  So I can just use wal.jpg in the custom.css for perfect-home as so:
`background-image: url("http://127.0.0.1:8000/wal.jpg");`

**Comment by kleshas** [comment]
Hi, still using this fantastic package after all these years.  Revisiting the css -  how to change the titles of each column (eg Perfect Home, TODO, Bookmarks Menu... in your comment on Jul 20, 2021 in this thread).  Mine stay white.  I guess I'm looking for a color-title: var(--color3); type of entry to put in .folder
