### ISSUE TITLE
Bug in thumbnail font

### ISSUE THREAD

**Issue by mly32** [perfect-things/perfect-home#136]
# Bug

## Problem

The descenders in the default font are getting cut off in the thumbnail.

![image](https://user-images.githubusercontent.com/52215742/135002439-3b8f171d-7caa-40f3-b0f7-e3a6b9690286.png)
Notice the `g`s.

The clipping is due to the overflow property being "hidden" in `item-thumb-suffix`.

## Solutions

Here are some suggestions:

1. Remove `overflow: hidden` from the relevant stylings (there could be other places this clipping happens).
2. Add some horizontal padding. For example, `padding: 1em 10px` produces:
  ![image](https://user-images.githubusercontent.com/52215742/135002837-a4c2cb33-cc52-4813-8329-b903867e9669.png)

**Comment by tborychowski** [comment]
Ok, I think I know why this happens!
I'm guessing you're not on mac and don't have `helvetica` font, in which case it falls back to `arial`, which behaves strangely and I can see this happening when I set it to arial on my machine.

I've naively set `line-height: 1;` assuming that all fonts abide by the rules, but it looks like `arial` doesn't.
My solution is to set the `line-height: normal;` which should default to `1.1` or `1.2`, depending on the platform and font-family.

**Comment by tborychowski** [comment]
Version 0.13.4 is now available in Mozilla extension gallery/store. Please update and let me know if you still see the issue :-)

**Comment by mly32** [comment]
Looks good! I had to uninstall and reinstall the extension in Firefox for some reason. Not sure why it did not automatically update. 

I recommend showing the version number somewhere in the settings panel in a future release.
