### ISSUE TITLE
Old good "new tab" page tiles of bookmarks in the form of screensots

### ISSUE THREAD

**Issue by CigarsSmoker** [perfect-things/perfect-home#138]
Hi,
Can you make or give me an advice to find/get/make using userChrome.css/userContent.css "new tab" page as Firefox 56 has?
With the same layout and functionality?
Please give me the answer to my email cjkm646@gmail.com - Vlad
Thank you in advance.
Good luck.

**Comment by tborychowski** [comment]
replied.
