### ISSUE TITLE
Option to exclude bookmarks dirs (for add-on speeding up)

### ISSUE THREAD

**Issue by kanlukasz** [perfect-things/perfect-home#139]
Hello.
A great add-on with a lot of potential!

## Initial outline of the issue 

For user like me with a lot of bookmarks, it's slow and lagging.
My guess is this is because:
![image](https://user-images.githubusercontent.com/30685349/141493827-4dabeb73-deb7-41aa-85be-d9462367d9ee.png)
Am i right?

**In my FF i have:**
![image](https://user-images.githubusercontent.com/30685349/141494185-71b23c7b-f722-45b8-8046-e93b15dd95dd.png)
_( this is a lot, i know, but many times it saved my life when I was looking for something old 😃  )_

## Feature suggestion
I got the idea that maybe there is a chance to exclude folders, so the API wouldn't have to download all bookmarks?
And maybe it could work faster thanks to this?

## GIF screen with an example of how it works in my FF - example 01
![output-onlinegiftools](https://user-images.githubusercontent.com/30685349/141496651-1b0749ef-5932-4c0c-9033-8888de0ae598.gif)

## GIF screen with an example of how it works in my FF - example 02

![tb912](https://user-images.githubusercontent.com/30685349/141496864-aa724b58-03be-46d3-9fef-7a0878fdb61b.gif)

**Comment by tborychowski** [comment]
16k!? masakra jakaś! :-D

No więc tak:
1. znudziła mi się ciągła walka z taką ograniczoną platformą jaką jest przeglądarka. firefox oczywiście głównie, ale i chrome i chromowe pochodne wszystkie klony, które różnią się niektórymi API, aż po safari, co to wymaga jakichś dziwów nieziemskich, żeby dodatek do niej napisać, wspiera może 5% standardowego API web extension i jeszcze oczekuje, że zapłacę kasę, żeby darmowy dodatek ludziom udostępniać przez app stora.

Dlatego nie planuję już dodawać większych ficzerów do tego dodatku, ani redezajnować go nazbytnio.
No a posiadanie 16k zakładek na czymś tak nietrwałym jak firefox tylko prosi się o jakąś klęskę :-)
(mam nadzieję, że chociaż bakapujesz regularnie 😉)
Dochodzimy więc do pkt 2:

2. Do takich rzeczy są lepsze "programy". Tu polecam apkę naszego rodaka - [pinboard.im](https://pinboard.in). Prosta i brzydka, ale działa cuda. Do tego są różne "nakładki" i klienty, wystarczy poszukać w necie (w zależności od OSa).

3. Ponieważ powyższa apka - choć działa - jest brzydka, mało giętka no i płatna (choć nie dużo), to planuję stworzenie trochę nowszej wersji, która będzie ładna, szybka i rozwiąże mi oba problemy: strony startowej dla przeglądarki (każdej przeglądarki - bez pisania dodatków) i przechowywania zakładek.

Także, przepraszam, ale przynajmniej narazie nie mam aż tyle wolnego czasu, żeby dodawać ficzery.

**Comment by kanlukasz** [comment]
Ok dzięki za info :-)
