### ISSUE TITLE
Kiwi Browser issue android

### ISSUE THREAD

**Issue by blogmangit** [perfect-things/perfect-home#140]
- tapping on quick tiles not working
- slider not working

Please make it mobile friendly

**Comment by tborychowski** [comment]
sorry, but I have no way of testing it!
I don't have an android device available. 
I also disable the option for mozilla to make it available to mobile firefox, but they keep resetting it with every new version.

If this kiwi browser would have a corresponding desktop browser (for mac) maybe it would be possible to check if it has the same problems, but otherwise, I see no way.
Unless you'd be able to debug it yourself and tell me what errors you see.
Does this browser have some sort of debug console?

**Comment by blogmangit** [comment]
> sorry, but I have no way of testing it!
> I don't have an android device available. 
> I also disable the option for mozilla to make it available to mobile firefox, but they keep resetting it with every new version.
> 
> If this kiwi browser would have a corresponding desktop browser (for mac) maybe it would be possible to check if it has the same problems, but otherwise, I see no way.
> Unless you'd be able to debug it yourself and tell me what errors you see.
> Does this browser have some sort of debug console?

yes kiwi browser has developer tool built in inside it.

**Comment by blogmangit** [comment]
![19_12_2021_16_16_13.jpg](https://user-images.githubusercontent.com/92579403/146672243-99eb659a-8990-4f68-89e1-f575696d3395.jpg)

![19_12_2021_16_15_49.jpg](https://user-images.githubusercontent.com/92579403/146672246-0cb30c59-6954-4779-8b64-723494205f2a.jpg)

How should I debug ?

**Comment by blogmangit** [comment]
I think there is some issue regarding the click event and touch event touches are not recorded as clicks on quick tiles

**Comment by tborychowski** [comment]
Wow, great!
1. So first thing would be to switch to "Console" tab and click on the tiles to see if you're getting any errors.
2. The tiles are normal a-href links, but if you have "Open in new tab" turned on, they are handled in javascript for obvious reasons.
3. Are you able to use any clickable elements? Like  clicking cog to open settings (or anything in settings)? If so - than the tiles should work too, unless there are some browser extension APIs that Kiwi does not support - in which case - you should see errors in the Console when you click one of them.

**Comment by blogmangit** [comment]
> Wow, great!
> 1. So first thing would be to switch to "Console" tab and click on the tiles to see if you're getting any errors.
> 2. The tiles are normal a-href links, but if you have "Open in new tab" turned on, they are handled in javascript for obvious reasons.
> 3. Are you able to use any clickable elements? Like  clicking cog to open settings (or anything in settings)? If so - than the tiles should work too, unless there are some browser extension APIs that Kiwi does not support - in which case - you should see errors in the Console when you click one of them.
> 

the problem is sometimes tiles are opening but other times they are not registering the taps on them it has become annoying also the sliders on touching is getting enabled but soon getting disabled automatically.

**Comment by blogmangit** [comment]
> Wow, great!
> 1. So first thing would be to switch to "Console" tab and click on the tiles to see if you're getting any errors.
> 2. The tiles are normal a-href links, but if you have "Open in new tab" turned on, they are handled in javascript for obvious reasons.
> 3. Are you able to use any clickable elements? Like  clicking cog to open settings (or anything in settings)? If so - than the tiles should work too, unless there are some browser extension APIs that Kiwi does not support - in which case - you should see errors in the Console when you click one of them.
> 

Attaching Video

https://www.dropbox.com/s/2qflaye8iorr72x/19_12_2021_21_10_59.mp4?dl=0

https://www.dropbox.com/s/wma1yvyifndtyzb/19_12_2021_21_21_48.mp4?dl=0

**Comment by tborychowski** [comment]
Thanks for the video. Unfortunately the errors in the console don't seem to be coming from my extension (I don't use jquery nor other scripts that show up there). Maybe you have some other extensions (at least a content blocker) that does throw some of these, while others seem to be coming from the sites you were able to open.

Can you do one more test for me:
1. Clean open the browser and the console (so the console is clear of any errors)
2. Have a link to something very simple, like `https://google.com`
2. Click that link just once to see if this produces any errors.

I just realised that there's no right-click on a mobile browser, so probably I should add a long-click to tiles :-)

**Comment by blogmangit** [comment]
> Thanks for the video. Unfortunately the errors in the console don't seem to be coming from my extension (I don't use jquery nor other scripts that show up there). Maybe you have some other extensions (at least a content blocker) that does throw some of these, while others seem to be coming from the sites you were able to open.
> 
> Can you do one more test for me:
> 1. Clean open the browser and the console (so the console is clear of any errors)
> 2. Have a link to something very simple, like `https://google.com`
> 2. Click that link just once to see if this produces any errors.
> 
> I just realised that there's no right-click on a mobile browser, so probably I should add a long-click to tiles :-)

yes I use ublock origin & I think there's no right click on mobile is something that might be doing it but I will try https://www.google.com and upload videos

**Comment by blogmangit** [comment]
> Thanks for the video. Unfortunately the errors in the console don't seem to be coming from my extension (I don't use jquery nor other scripts that show up there). Maybe you have some other extensions (at least a content blocker) that does throw some of these, while others seem to be coming from the sites you were able to open.
> 
> Can you do one more test for me:
> 1. Clean open the browser and the console (so the console is clear of any errors)
> 2. Have a link to something very simple, like `https://google.com`
> 2. Click that link just once to see if this produces any errors.
> 
> I just realised that there's no right-click on a mobile browser, so probably I should add a long-click to tiles :-)

New link attached I also disabled my only extensions ublockorigin & auto history wipe. 

https://www.dropbox.com/s/83hemoaedvpd4if/19_12_2021_21_29_34.mp4?dl=0

**Comment by tborychowski** [comment]
Thanks, that's very useful.
So it works the first time, but when you go back and click again - it doesn't?

**Comment by blogmangit** [comment]
> Thanks, that's very useful.
> So it works the first time, but when you go back and click again - it doesn't? 

yes exactly that the issue also toggle buttons not enabling on touch

**Comment by tborychowski** [comment]
Ok. 
As there are no errors from the extension and it does work (the first time it's open), I'm afraid it looks like a browser problem. Browsers usually cache pages, for performance, so when you click back - they are loaded instantly, and in this case the "freeze all scripts" that is applied to this cached page - does not unfreeze scripts properly for some reason.

What I can do is to try to detect that it runs on mobile, and maybe disable the javascript handling of the links and default to the normal link behaviour, which should work normally. 
Leave it with me. 
I'll do some tests and see what I can do.
(may not be today, but as soon as I have a moment)


Toggles are a different story. 
I'll test them out again and see if I can reproduce (as I can do that in isolation, without the extension).

**Comment by blogmangit** [comment]
> Ok. 
> As there are no errors from the extension and it does work (the first time it's open), I'm afraid it looks like a browser problem. Browsers usually cache pages, for performance, so when you click back - they are loaded instantly, and in this case the "freeze all scripts" that is applied to this cached page - does not unfreeze scripts properly for some reason.
> 
> What I can do is to try to detect that it runs on mobile, and maybe disable the javascript handling of the links and default to the normal link behaviour, which should work normally. 
> Leave it with me. 
> I'll do some tests and see what I can do.
> (may not be today, but as soon as I have a moment)
> 
> 
> Toggles are a different story. 
> I'll test them out again and see if I can reproduce (as I can do that in isolation, without the extension).
> 

That's great thanks

**Comment by tborychowski** [comment]
Hi.
So I just released a new version of the extension (0.13.9).
I've fixed the toggle control so it should work on touch devices now.
However I wasn't able to reproduce your other issue, when after going back to the extension page (from a link) - clicking on tiles doesn't open the links.
To me it looks like it's a browser thing - it tries to freeze scripts, so cached history is lighter and waking them up after clicking "back" doesn't work for some reason.
Unfortunately, I have no way to debug that 😞 

Have you tried this in the mobile Firefox? Do you know if it works there?

**Comment by blogmangit** [comment]
> Hi.
> So I just released a new version of the extension (0.13.9).
> I've fixed the toggle control so it should work on touch devices now.
> However I wasn't able to reproduce your other issue, when after going back to the extension page (from a link) - clicking on tiles doesn't open the links.
> To me it looks like it's a browser thing - it tries to freeze scripts, so cached history is lighter and waking them up after clicking "back" doesn't work for some reason.
> Unfortunately, I have no way to debug that 😞 
> 
> Have you tried this in the mobile Firefox? Do you know if it works there?

unfortunately mobile firefox android doesn't support extensions which changes homepage because they don't even have the option to customize homepage to something other than theirs. But thanks a lot
