### ISSUE TITLE
new functionallty

### ISSUE THREAD

**Issue by kleshas** [perfect-things/perfect-home#146]
First off, still loving this project.  Good job with it.

I have somewhat of a custom setup - 6 permanently shown columns, full of links, grouped by subject (each column is a bookmark folder full of shortcuts).  As I'm running out of space, I'd love to have the functionality to click on a link to open a new perfect home page, full of links from another bookmark folder that isn't one of the folders on the original page.   The closest I've come to this is having the new link open a custom css/html local file with manually edited links to websites (plus changing a few settings to allow firefox to be able to click on local file links...) (this custom page is how I used to do a startpage before I discovered PH).  While this works, it misses the perfecthome functionality of meshing with the browser's bookmarks eg ctrl-D, and refresh showing the new link.

**Comment by tborychowski** [comment]
Haha, thanks for kind words, but as for bookmarks... I think you may be doing it wrong :-)

If you have more than 100 bookmarks, that's too many, and you don't need a speed-dial-home-page, but rather a bookmark archive, like [pinboard](https://pinboard.in) or self-hosted [linkding](https://github.com/sissbruecker/linkding), which is what I use for this purpose.

Unfortunately, neither my extension, nor even Firefox bookmarks are designed for large numbers of items.
In my tests I've noticed that even querying Firefox' bookmarks API gets substantially slower with the number of bookmarks, and becames almost unusable with a 1000+ bookmarks (unless that changed recently, I haven't tested it for a while).

So, I feel your pain and understand the reasoning, but to make it work like you've described, would mean a significant redesigning of the extension, and a lot of dev effort, for which I have neither the time nor motivation.

I have abandoned Firefox for Safari a while ago, and I do miss my extension (Safari does not provide bookmarks API yet, so I can't port it there), but I am forced to use something else.

**Comment by kleshas** [comment]
Alright, fair enough.  I appreciate the explanation. :)
