### ISSUE TITLE
Option to change default state shorcut icons look for all shortcut icons.

### ISSUE THREAD

**Issue by Apofen** [perfect-things/perfect-home#148]
It would be great to have an option to change how shortcut icon looks in default state by change to grayscale and / or set brightness. All icons appearance could change to default look on mouse hover with fade in effect.

**Comment by tborychowski** [comment]
That is what `Custom CSS` is for!
Everyone's esthetics is different, and the customization options of this extension should allow for a lot of diversity in styling and layout.

The extension allows for custom icons for your bookmarks as well as styling them with CSS to whatever you wish.
Here's a simple tutorial for customization: https://github.com/perfect-things/perfect-home/blob/master/customization-tutorial.md

As for changing the icons - you can use icons from built-in themes. To do that you need to:
1. Enable `Allow Github` option in `Privacy` section of the Settings sidebar
2. Select an icon theme in the `Customize` section of the Settings sidebar
3. Right click any bookmark tile and click `Edit` from the context menu
4. Click `Pick from theme` button in the popup dialog.

More on theming: https://github.com/perfect-things/perfect-home-themes#perfect-home---themes
