### ISSUE TITLE
Folders suck, "group by" tags?

### ISSUE THREAD

**Issue by morphles** [perfect-things/perfect-home#150]
I find folders extremely limiting and even more fiddly to maintain in any sensible organization (if that is even possible, considering one thing can have multiple criteria overlapping in many other things in many ways - hence tags). Thus it would be extremely nice and amazing to be able to choose not folder but tag to be displayed, and same for having "docked tags".

**Comment by tborychowski** [comment]
Thanks for the suggestion with a click-baity title ;-)

Unfortunately, this would require a lot of work (like couple of weeks with proper testing) to redesign the whole thing, and I have neither time, nor motivation to add more features.
I no longer use it myself, and, I have no time to spare.

At least for now, I consider the extension feature complete, and in maintenance mode, so I only fix bugs if there are any reported.
And there hasn't been one for over a year, which is pretty good, considering over a 1000 people use it every day on different browsers.

Lastly, I consider tags to be far inferior to folders, so I don't thing this feature would make it to any roadmap for this extension :-)
But you're free to fork and work on it yourself, if you have time, skills, and the need :-)
