### ISSUE TITLE
Mobile firefox addon 

### ISSUE THREAD

**Issue by anwaruddin2k** [perfect-things/perfect-home#153]
Now starting from mozilla firefox 120 . It supports addon. Do you have plans for Android support in future releases.

**Comment by tborychowski** [comment]
Hi,
No, unfortunately, I don't have access to android device, and even if I did, I just don't have the time, anymore, to develop software for other people for free :-)

**Comment by anwaruddin2k** [comment]
> Hi, No, unfortunately, I don't have access to android device, and even if I did, I just don't have the time, anymore, to develop software for other people for free :-)

Thanks for your response. I can understand :)
