### ISSUE TITLE
Remove Search Bar Animation

### ISSUE THREAD

**Issue by eeriemyxi** [perfect-things/perfect-home#154]
Could you perhaps add an option in the settings to disable the search bar animation that it does when you try to launch the search bar?

https://github.com/perfect-things/perfect-home/assets/86738916/0e888cf0-e795-4886-9f7e-c06965ad6387

It days a delay before which I can input into the search and I find that unnecessary.

**Comment by tborychowski** [comment]
It's easy to do with the custom css. Add this line in Settings/Customize/Custom CSS box:
```css
.search-modal,
.search-modal .modal { transition: none; }
```

This will disable all animations/transitions on the search modal (and its backdrop).
