### ISSUE TITLE
Unhandled Exception for Missing Titles

### ISSUE THREAD

**Issue by thompcd** [perfect-things/perfect-home#2]
When a shortcut exists with an empty string for a name, an exception is thrown:

`TypeError: l.title[0] is undefined index.js:1:17792`

This also prevents the menu from responding, so a user is unable to change the monitored directory.

**Comment by tborychowski** [comment]
That's fixed and will be released in v0.2.2 (as soon as mozilla reviews it).
btw. if you just want to hide the labels (or a single label) you can do that easily with "Custom CSS".

**Comment by thompcd** [comment]
Thanks @tborychowski !
 It's not that I wanted to get rid of the labels, it's that they were already gone so they were icons only on my toolbar. In that situation all of the coloring of the tiles and the titles for the ones that do exist break also. I saw that dragging all of those 'icon-only' bookmarks into a folder fixed this issue, which is why I proposed the solution as it were.
I appreciate you making your project public, it's pretty awesome. :)

**Comment by tborychowski** [comment]
Thanks! :-)
The weird thing was (and I think it's actually a bug in Firefox) - when you create a bookmark with name, save it and then remove the name - it was working fine.
However, if you remove the name before saving the bookmark - it was failing (at least in my case).
Which means that firefox wasn't saving the name as empty string, but as `null` or similar.
Anyways, it should work fine now.
Please do let me know if you have any other issues.
