### ISSUE TITLE
Right-click -> Open in new tab/window

### ISSUE THREAD

**Issue by lucasbianchi** [perfect-things/perfect-home#48]
Hi,
I am used to work with Opera, now I'm trying to comeback to Firefox once more and I've discovered your great extension. Thanks!

Like in Opera,  I think it would be nice to have the option of "Open in new tab" or "Open in new window"...among others, when you right-click an icon.

Thanks!
Lucas.

**Comment by tborychowski** [comment]
Thanks! I will have a look

**Comment by tborychowski** [comment]
this will be available in the next release
