### ISSUE TITLE
Add css validator to "Custom CSS" field

### ISSUE THREAD

**Issue by tborychowski** [perfect-things/perfect-home#59]
ref: #18

**Comment by Vldm11r** [comment]
It turned out great, I like how it works.

**Comment by tborychowski** [comment]
Thanks. I've spent hours searching for client-side css validation, and, as crazy as it sounds, there is none!
So just doing a very basic validation there:
- number of `{` matches number of `}`
- if there's text - there should be at least 1 css rule
