### ISSUE TITLE
Ability to change the folder shortcut.

### ISSUE THREAD

**Issue by Vldm11r** [perfect-things/perfect-home#60]
When there are too many folders, they differ only in text. The ability to change color, add an icon or change a shortcut would not hurt.

**Comment by tborychowski** [comment]
- you can change the thumbnail in the "edit"  modal window to any image or URL of an image, like so:
<img width="901" alt="Screenshot 2020-01-17 at 20 49 32" src="https://user-images.githubusercontent.com/392513/72645205-f18ba980-396a-11ea-8c23-e59157be51de.png">

- shortcuts I dont' want to do, as that is a bit of a mess and they always conflict with so many other shortcuts inn the system & browser
- there's also a command palette thing (CMD+P on mac, WIN+P on windows) where you can quickly open any bookmark you have. The only problem is that the page must have the focus, and by default Firefox focuses the address bar (and there's no way to programmatically change that). So the only way is to hit tab a couple of times. Give it a shot and let me know.

**Comment by tborychowski** [comment]
oh, sorry, you meant folders! :-)
yeah, I'm thinking about this. 1 idea is to do it like safari/vivaldi:
<img width="191" alt="Screenshot 2020-01-17 at 20 52 39" src="https://user-images.githubusercontent.com/392513/72645345-52b37d00-396b-11ea-881a-d00ca753722d.png">
basically show thumbs of items inside the folder.

**Comment by Vldm11r** [comment]
> basically show thumbs of items inside the folder.

Good idea, will these be from the last 4 bookmarks stored in this folder?

**Comment by Vldm11r** [comment]
How did you make all the labels in the rectangles? It looks more attractive than mine.
![изображение](https://user-images.githubusercontent.com/59932374/72646642-476a4c80-397f-11ea-87be-16ee36a4b261.png)

**Comment by tborychowski** [comment]
It's just a rectangle image, e.g.:
![youtube-dark](https://user-images.githubusercontent.com/392513/72648420-e9d00300-3972-11ea-9619-5d5d495e80d6.png)

If you have Sketch app for mac - I can share my template.
(another idea I have for the future is to have a common repository of these thumbnails/icons, where people can share and re-use them)

**Comment by Vldm11r** [comment]
> (another idea I have for the future is to have a common repository of these thumbnails/icons, where people can share and re-use them)

Repositories are great things, the only question is, if they can add everything, then how to control it?

**Comment by Vldm11r** [comment]
> If you have Sketch app for mac - I can share my template.

Maybe you know something for windows?

**Comment by tborychowski** [comment]
https://alternativeto.net/software/sketch/?license=free&platform=windows

I heard some good things about figma (haven't used it myself).
