### ISSUE TITLE
Add ability to automatically colapse docker folders

### ISSUE THREAD

**Issue by boozejedi** [perfect-things/perfect-home#61]
Suggested default or configurable behavior

- fodlers are always colapsed when new tab or home is opened
- fodlers should collapse if container lost focus, for example, body was clicked

**Comment by tborychowski** [comment]
Hi,
Thanks for your contribution.
Could you explain the use case for these options?

For example - the current behaviour covers these 2 use cases:

**Use Case 1 - TODO folder**
- I create a docked folder so I can store my "TODO" bookmarks
- I want to see my docked folder expanded, so whenever  I create a new tab - I see my "TODO" list

**Use Case 2 - a project folder** 
- I create a docked folder that contains bookmarks associated with a project that I'm working on
- I want to see my docked folder collapsed (to remind me of the project, by name), but not  all of its bookmarks
- I want to be able to expand this folder only when I work on this project

---

Currently docked folders remember their last state which covers both use cases very well.
I feel that adding these config options would make it unnecessarily complex and (maybe even) confusing. I.e. for every docked folder you'd have:
- Folder name (select box)
- Always expand, always collapse, remember last state (3 radio buttons)
- Collapse when clicked outside of the folder (checkbox) - that one is probably the most confusing... why would anyone want to do that?

**Comment by boozejedi** [comment]
Hi,

Here is my use case.

I have a 3 folders with a different types of documentation with roughly 100 links in total.
I would like to pin this folders as a docked folders so I can access my documentation links quickly.
Usually I access this links 1-10 times a day.
Once I open a link from docked folder and then open a new tab again I would like docker folder to be collapsed as the content of the folder is not interests me anymore.
Additionally, an expanded docked folder hides links from main folder that is in the middle of the screen that I access much more frequently.

As for collapsing docked folders after losing a focus, it's kind of similar behaviour of built-in menus in the browser. For example, if I would open LIbrary menu if would show me its content but if would click somewhere else the menu will close. A use case for this is accidental clicks or "change of mind" situation.

Suggestion for configuration would be to have only one toggle. First default state could be as it currently behaves, second as it described above.

While collapsing docked folders after losing a focus is more of a comfort feature but opening a new tab with a docked folders always collapsed is a highly desired one.

No matter what you would choose to go with, I would like to thank you for giving us a great addon.

**Comment by tborychowski** [comment]
Now this makes perfect sense.
So much that I am now considering tweaking the default behaviour... 😄 

My proposition is this:
- by default all docked folders will be closed/collapsed
- you can click on a folder to expand it
- the expanded folder will collapse if you click away or reload the page (this includes opening the new tab)
- however, you will be able to "pin" the open/expanded docked folder by clicking a "pin" icon next to the folder name, and it will stay expanded (even for new tabs) (this is the same behaviour as current "expanded" docked folder)

This should cover your use case as well as make the docked folders be more "docked".
What do you think?

**Comment by boozejedi** [comment]
Sounds perfect! It's a great idea to have individual pins.

**Comment by tborychowski** [comment]
this will be available in the next release
