### ISSUE TITLE
Local file bookmarks do not open when clicked.

### ISSUE THREAD

**Issue by KeelyHill** [perfect-things/perfect-home#65]
Example: I have a local folder (or file) bookmarked. `file:///home/user/Documents/PDFLinks/`, clicking on it from the Perfect Home new tab does nothing. Opening from standard bookmarks bar works fine. The thumbnail just says "undefined".

Am I doing something wrong, or is this a bug? Thanks.

**Comment by tborychowski** [comment]
Looks like a bug. Let me have a look.

**Comment by tborychowski** [comment]
looks like this is prevented for security reasons...
https://bugzilla.mozilla.org/show_bug.cgi?id=995943

**Comment by tborychowski** [comment]
adding these properties manually in `about:config` fixes the problem:
- `capability.policy.policynames` set to `localfilelinks`
- `capability.policy.localfilelinks.checkloaduri.enabled` set to `allAccess`
- `capability.policy.localfilelinks.sites` set to `moz-extension://ae713ee4-9617-1948-ae55-cefc81ae55f1/index.html` (the long ID number is the ID of this extension)

**Comment by tborychowski** [comment]
Unfortunately this doesn't seem to be fixable (at least not without hacking) so I'm gonna add a FAQ item with the above workaround and some popup (when you click a local link) to explain why it doesn't work and what to do.

**Comment by KeelyHill** [comment]
Thanks for looking into this! The work around (and popup) worked for me.
