### ISSUE TITLE
Enable "search bookmarks" for windows

### ISSUE THREAD

**Issue by trevanian** [perfect-things/perfect-home#70]
Hi there,

Thank you very much for great plugin. Only thing I found missing is Search in Bookmarks feature. I hope you can be able to add that. I can't wait for that.

Alll the best,
Uğur

**Comment by tborychowski** [comment]
have you tried the command palette?
It's an experimental feature, that currently is only available for mac:
you need to focus the page and hit CMD+P
and you'd see sth. like this:
<img src="https://raw.githubusercontent.com/perfect-things/perfect-home/master/_stuff/screen-palette.png" width="500">
that allows you to fuzzy-search all bookmarks

**Comment by trevanian** [comment]
Unfortunately I'm using windows. I can recommend to review this chrome extension, actually it does what I need but I don't want to use chrome.

https://chrome.google.com/webstore/detail/visual-bookmarks/jdbgjlehkajddoapdgpdjmlpdalfnenf

**Comment by tborychowski** [comment]
Thanks. (I don't want to use chrome either 😄)
Moreover, I don't want to add a search text box to the page itself, as this looks ugly.
Also, the same functionality would not make sense for my extension. 
The linked chrome addon searches within the selected folder (which - if you have fewer than 20 bookmarks - is pointless; if you have more than 20 - maybe it's a better idea to sort them into folders).
My "Command palette" searches in all folders, which makes more sense (at least to me).

I will enable that function for windows in the next release, so you can have a look and see if that works for you, ok?

**Comment by trevanian** [comment]
That's ok to me. Btw I have 1185 bookmarks currently and all sorted in folders still in need search in folders. Thank you for your time. Waiting for next release :)
