### ISSUE TITLE
Fix "Search" animation to match the overall UX

### ISSUE THREAD

**Issue by tborychowski** [perfect-things/perfect-home#71]
from @Vldm11r

> Hello, I didn’t know in which branch to write, I recently noticed that a search appeared and I began to use it very actively, it would be great if the search menu was turned on with the same effect as editing a bookmark.

**Comment by tborychowski** [comment]
@Vldm11r
You can always create a new issue, instead of adding comments to random, completely unrelated ones :-)

And regarding the search - I don't think I understand what you mean by 

>turned on with the same effect as editing a bookmark.

Do you mean the animation?

**Comment by Vldm11r** [comment]
> You can always create a new issue, instead of adding comments to random, completely unrelated ones :-)

I'll keep it on mind.

> Do you mean the animation?

Yes, I mean animation)

**Comment by tborychowski** [comment]
Ha! Good idea. I haven't used both in the same time, so I didn't even noticed! :-)
