### ISSUE TITLE
reader links dont work

### ISSUE THREAD

**Issue by tborychowski** [perfect-things/perfect-home#74]
e.g.: about:reader?url=https%3A%2F%2Fblog.cloudflare.com%2Fthe-history-of-the-url%2F

**Comment by Vldm11r** [comment]
What kind of link reader?

**Comment by tborychowski** [comment]
Firefox has a built-in "reader view" - when you visit a blog or a page with an article, you can click on an icon in the right of the url-bar and switch the reader view for distraction-free reading.
(or just copy the link I've pasted in the comment above).
