### ISSUE TITLE
No keyboard navigation possible to scroll the page

### ISSUE THREAD

**Issue by cengels** [perfect-things/perfect-home#81]
While this is not a high-priority issue, it would be nice to see keyboard navigation work inside Perfect Home. This includes the following standard shortcuts:

- Arrow Up: should move the page up by one scroll motion
- Arrow Down: should move the page down by one scroll motion
- Home: should move the page to the top
- End: should move the page to the bottom
- Page Up: should move the page up by one full page
- Page Down: should move the page down by one full page

Sorry for "spamming" the issues tab. I'm just noting down what I'm noticing while using the extension. This problem doesn't necessarily bother me, I just found it odd that those shortcuts didn't work.

**Comment by tborychowski** [comment]
Hi,
No need to apologize! You're helping me make it better!
Thank you for this! :-)

And in regard to the shortcuts - they do work, if the focus is on the scrollable part of the page.
Try hitting <tab> couple of times until you see an outline (dotted line) around the first bookmark on the page - arrows should work now (at least they do for me).
If not, please let me know.
Are you using windows, mac or linux?

**Comment by cengels** [comment]
Oh, I just tested it and you're (partly) right. Tabbing once redirects the focus to the scrollable part of the page, which makes the keys work.

However, the big problem is that using the tab key appears to actually be the only way to achieve that. Hitting any of the arrow or page up/down keys does not focus that part of the page, nor does clicking anywhere (even on the scrollbar!) do. Can you reproduce this on Mac (which I believe is what you're using, right?)? I'm on Windows, Firefox Nightly v76.0a1 (though I don't think Firefox is to blame here since it works fine on other websites).

I noticed that the `body` uses the `autofocus` attribute. While I don't think that's the problem, I'd be curious to know if it actually does anything since according to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefautofocus), only input elements can have this attribute.

**Comment by tborychowski** [comment]
Ha! You're right, `autofocus` probably doesn't do much on `body`.
Especially because it's not the right element! ;-)
The scrollable element is `main` in this case and that one should be focused!
I'll fix that.

**Comment by tborychowski** [comment]
Actually it seems that body is the scrollable part after all.

I added a click event on document, so now, when you click anywhere (not on anything interactive) the body will receive the focus, and you can scroll with arrows.
Obviously you can also hit `tab` to get to body too.

Unfortunately browser intercepts the focus when you open a new tab (focus lands on address bar), and there is no programmatic way to force focus on page load (in an extension that is).
