### ISSUE TITLE
Not working on Linux Waterfox :(

### ISSUE THREAD

**Issue by ObiSandwich** [perfect-things/perfect-home#82]
Waterfox 2020.03 (64-bit)
Linux Mint LMDE 3

Can't get this add-on to work :( Been a FVD Speed Dial user for years and really want to give this one a go, please help?

I have installed this add-on multiple times ok and I have allowed all permissions, but doesn't seem to work - eg. Clicking on the Settings cog or Search magnifier doesn't do anything other than glow orange. I have even tried an earlier version of the add-on.

I have restarted the computer and browser. I have disabled all other add-ons and changed the browsers Content Blocking from Strict to Standard.

Unsure how to add a bookmark/dial, but if this add-on is not working properly, then I guess I'm not seeing all the options right?

Thanks,

**Comment by tborychowski** [comment]
Hi @ObiSandwich,

Firstly, this addon is meant for Firefox. I haven't even tested it in any other browsers.
I can have a look when I have more time and see what's the problem there, when I have a bit more time.
Hopefully it's something simple.
Can you let me know which version are you using: Current or Classic (not sure what's the difference, but I want to test it on the same one that you have).

As for how it works: in settings you have a dropdown with all the folders from your bookmarks.
You can select a folder and have the speed-dial-like* page displayed.

*This is not a speed-dial extension. It shows your own bookmarks. 
😄

**Comment by tborychowski** [comment]
this is the same issue as #85 
closing as duplicate.
further progress will be tracked there.

**Comment by tborychowski** [comment]
apparently not the same issue :-)

**Comment by tborychowski** [comment]
This happens because Waterfox does not support [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver).
Fix on the way.

**Comment by tborychowski** [comment]
This should be fixed in the latest version 0.10.0.
Please reopen the issue if you still see the problem.
