### ISSUE TITLE
Firefox Android

### ISSUE THREAD

**Issue by bhnettv** [perfect-things/perfect-home#83]
Hello. Is it posible to make this addon work on firefox mobile?
Thanks

**Comment by tborychowski** [comment]
It doesn't work?
Mozilla user stats shows users with firefox mobile too?

**Comment by bhnettv** [comment]
I dont know. Extension is enabled and there is no posibilities to change about:home which is default firefox home screen.

**Comment by tborychowski** [comment]
🤔 
Have you (or could you) tried any other extensions that replace the home screen?
Do they work?
If not, than that would probably be another firefox restriction.
If they do work - than there's a chance I could fix it too.
It will be difficult though, as I have no access to an android device 😐

**Comment by bhnettv** [comment]
one that work is bitbiz newtab bu i have to change home address to point to:
moz-extension://5caf1780-6061-48eb-ac8f-68abfd48db6a/momentum.html

another thing is that I dont see any options on android just enble/disable and uninstall

**Comment by tborychowski** [comment]
> another thing is that I dont see any options on android just enble/disable and uninstall
what do you mean? you can't uninstall my extension?

as for adding specific extension URL as homepage - this should also be possible. You'd just need to know the ID that your firefox assigns to this extension.
As a part of this issue #53 I'll be adding a button to the extension toolbar, which will open the perfect home specifically. From there you should be able to pick up the URL (with the ID).
Maybe that would help?

Sorry, but I'm not sure how otherwise I could debug that without a device...

**Comment by bhnettv** [comment]
this is the manifest of bitbiz 
{
  "manifest_version": 2,
  "name": "Bitbiz New Tab",
  "version": "1.0",
  "description": "Bitbiz New Tab by BitBiz.nl",

  "browser_action": {
    "default_icon": "logo.png",
	"default_popup": "popup.html"
  },

    "chrome_url_overrides": {
      "newtab": "momentum.html"
    },

  "permissions": [
    "activeTab",
    "https://ajax.googleapis.com/",
    "geolocation"
  ]

and I somehow managed to start your app but got undefined on main screen with two buttons settings and search neither work

**Comment by tborychowski** [comment]
Thanks for that.
This actually looks similar to the other issue: #82, which gives me an idea that I can test (in waterfox).
It's possible that the default bookmark folder, that the extensions selects, is not there (in both cases: android & waterfox) and it fails there, preventing the rest of the extension to work...
Let me do some tests.

**Comment by tborychowski** [comment]
this is the same issue as #82
closing as duplicate.
further progress will be tracked there.

**Comment by tborychowski** [comment]
This happens because Firefox for Android does not support [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver).
Fix on the way.

**Comment by tborychowski** [comment]
This should be fixed in the latest version 0.10.0.
Please reopen the issue if you still see the problem.
