### ISSUE TITLE
If extension page is scrollable, main folder dropdown immediately closes

### ISSUE THREAD

**Issue by cengels** [perfect-things/perfect-home#84]
If there are enough bookmarks to overflow the page (i.e. a scrollbar appears on the right side), opening the dropdown for the main folder in the settings immediately closes the dropdown on mouseup. The only way to avoid this is to release the mouse outside of the select element. That way the dropdown stays open.

I have been able to consistently reproduce this on a clean Firefox Nightly (77.0a1) user profile on Windows, but let me know if you need more information.

**Comment by tborychowski** [comment]
Yeah, I tested that in Nightly and it happens there.
However, this doesn't happen in a stable (or beta) versions of firefox, so this must be something with the Firefox Nightly.
(I was using Nightlies for a couple of months some time ago and found them very unstable and full of bugs, so not surprised).
As this is a html native control (`<select>` tag) there's really nothing I could do to fix that.
I can only advise you to not use Nightly :-)

**Comment by cengels** [comment]
That's strange. I can reproduce this on the stable version of Firefox as well, though I appear to have been wrong again—it seems as though this issue is actually the same as #79. I could have sworn I saw this behaviour independently of the bug in #79 at one point, but now I can't reproduce it without also simultaneously reproducing #79 anymore (i.e. using the same set of conditions).

**Comment by tborychowski** [comment]
Ha! you're right!
I just reproduced it!
Another factor that must be fulfilled is that the dropdown is bigger than the browser window.
I popped up the dev tools (so that the dropdown hides under it) and this happens.

**Comment by tborychowski** [comment]
the fix for #81 broke it 😕 
it does seem like a firefox issue TBH... 
I managed to pinpoint it to the selected item in the dropdown (14th works, 15th doesn't).
Anyway, fix on the way!

**Comment by tborychowski** [comment]
This should be fixed in the latest version 0.10.0.
Please reopen the issue if you still see the problem.
