### ISSUE TITLE
Allow to use favicons

### ISSUE THREAD

**Issue by rastersoft** [perfect-things/perfect-home#89]
Hello:
I want to make a suggestion: I would really love to be able to use the favicons automagically for each entry.
Thanks for this great extension.

**Comment by tborychowski** [comment]
Thank you for your feedback.

Yeah, I'd love to have that feature. 
However, this doesn't seem to be possible with the current constraints that I have (and want to have) and current restrictions that mozilla enforces.

Please see my answer in a similar issue: https://github.com/perfect-things/perfect-home/issues/37#issuecomment-546635708

**Comment by tborychowski** [comment]
Feel free to reopen the issue if you have any further information.
