### ISSUE TITLE
Address bar is not focused in new tabs

### ISSUE THREAD

**Issue by amiraliakbari** [perfect-things/perfect-home#95]
When Perfect Home is enabled as the default new tab page, the address bar loses the focus when a new tab is opened. It makes it difficult to only use keyboard for quickly doing a search or opening a URL.

Without this addon, pressing Ctrl+T opens a new tab with the address bar having the focus, and also the tiles showing in the page. But with Perfect Home, you have to do Ctrl+T and then Ctrl+L to have a similar experience.

**Comment by tborychowski** [comment]
That's weird that you're getting this problem.
I cannot reproduce it.
And, what's more it's not even possible to make it work like you describe, as the focus is controlled by the browser and extensions cannot intercept it or force to focus anything (as long as the focus remain outside of the page itself).

Can you determine where is your focus after opening a new tab?
Can you also provide some more details, like:
- OS name & version
- Firefox version
- Extension version (I assume it's the latest one?)
What would also help is if you could record a gif an post it here.

Thanks!

**Comment by amiraliakbari** [comment]
I'm using Nightly 80 on Linux. The problem is not occurring in a normal 78 build, probably it is a temporary problem in Nightly :confused: .

Regarding the focus, there is no visible element having the focus. Pressing the tab once put focus on the plugin's search icon.

**Comment by tborychowski** [comment]
Thanks. Yes, it might be a problem in nightly. I'll get it anyway and have a look.

**Comment by amiraliakbari** [comment]
The issue is solved in latest Nightly. Thanks for your consideration.
